### ISSUE TITLE
Service

### ISSUE THREAD

**Issue by Griffen8280** [ebrianne/adguard-exporter#1]
Love the work your doing with this.  I have integrated it into my AdGuardHome server and created a service file and helper script in order to run this application as a systemd service.  I would be more than happy to provide you the files if you would like to integrate them into your project.  I can even write a service installation script (I have done this previously in my own projects) to automate service installation and integration.

**Comment by ebrianne** [comment]
You re welcome to contribute to it! I have set up the systemd on my pi and it could be added in the README or provided as a file already.

**Comment by Griffen8280** [comment]
Awesome, I'll see if I can figure out the branch system here and get something added.
