### ISSUE TITLE
Question...not an issue

### ISSUE THREAD

**Issue by jleboube** [ebrianne/adguard-exporter#11]
I am curious if this product is intended to only run on the AdGuard host (192.168.1.254) or if this can run anywhere on the network (192.168.1.100) and interrogate the AdGuard host (192.168.1.254) for these metrics?  The fact that it is an exporter leads me to believe it is required to run on the AdGuard host, but I wanted to check to be sure.  Sorry in advance for my ignorance.

**Comment by DanSman** [comment]
Little late but doesn't matter :)

You can run it everywhere you want. Just type your AdGuard web - username, passwd and ip into the docker config file or whatever you use.

**Comment by ebrianne** [comment]
Sorry I have been a bit overbooked lately and forgot about this. Exactly as @DanSman said.
