### ISSUE TITLE
Dashboard is not compatible with Grafana v8

### ISSUE THREAD

**Issue by ngosang** [ebrianne/adguard-exporter#12]
Could you provide another Dashboard fro Grafana v8?
- Pie chart is now included in Grafana
- Tables require different options

**Comment by ebrianne** [comment]
I reopened it. However I won't make an update for the dashboard. If you feel like it you can contribute by making a PR with the necessary changes. Thanks!

**Comment by Skoetting** [comment]
HI @ngosang,
As a workaround you can simply install the "old" plugin on Grafana 8, see https://grafana.com/grafana/plugins/grafana-piechart-panel/

Or edit the Dashboard JSON by yourself and replace all "grafana-piechart-panel" with "piechart" to make it work

**Comment by mateoops** [comment]
Can you reopen? I would like to make PR with changes.
