### ISSUE TITLE
[enhancement] Add metric(s) to show use and performance of upstream servers

### ISSUE THREAD

**Issue by beneix** [ebrianne/adguard-exporter#15]
I use AdGuardHome with a pool of 6-10  upstream providers and have set AdGuard to use them in load-balancing mode. It would be cool to be able to see how well they perform, for example with metrics such as:

- Each resolver's share of queries handled
- Each resolver's share of queries handled over time (AdGuard supposedly favours the faster ones using a weighted random algorithm)
- Each resolver's average response time
- Each resolver's average response time over time

**Comment by ebrianne** [comment]
Hi! Thanks for the suggestion. I ll have a look into it when I have some time.

**Comment by mvadu** [comment]
this may be a request to upstream repo. `/control/stats` endpoint used by this repo to pull stats does not have anything about resolver performance.

**Comment by ebrianne** [comment]
I agree there is nothing from the API for this. It would need to be asked to the Adguard team to implement such feature so that the exporter can query the API for such stats.
