### ISSUE TITLE
Question: Multiple AdguardHomeInstances

### ISSUE THREAD

**Issue by neruve** [ebrianne/adguard-exporter#25]
Does this support polling together multiple AGH instances? I actually have two instances running and am about to have a third for failover/backup reasons. I would love to be able to grab the data from all of them and blast it into one dashboard. Is that possible with this? If so, how would I set that up in the config or env variables?

**Comment by ebrianne** [comment]
At the moment, this is not possible. You can spin 3 exporters and use the data exported into one dashboard.
