### ISSUE TITLE
Failing to login on ARM64 Docker

### ISSUE THREAD

**Issue by Satellite-Galaxy** [ebrianne/adguard-exporter#28]
When trying to use this project on a Raspberry PI 4 under docker it always crashes with
>  An error occured in the request, Status Code 403

And spams Adguard with

> auth: invalid Basic Authorization value

I know that the password is right because I logged into the dashboard with it and I tried this project on my desktop pc (not in a container) and it connects just fine.

Do you know what would be causing this?

**Comment by szibis** [comment]
This issue also exists on Docker 32bit the same issue with the latest adguard home.
