### ISSUE TITLE
Specify a custom port ?

### ISSUE THREAD

**Issue by SkYNewZ** [ebrianne/adguard-exporter#4]
https://github.com/ebrianne/adguard-exporter/blob/7571d78c9c08e9f80a59074d48222ff9ea7012b1/internal/adguard/client.go#L53

I'm currently not using AdGuard Home on port 80 nor 443. Can you please provide a argument to specify a custom port different from standard http/https ones please ?

**Comment by ebrianne** [comment]
Sure I'll have a look into it.

**Comment by ebrianne** [comment]
Can you check now with the master if that works for you?

**Comment by ItsMeFishy** [comment]
I got the same issue and just tried with new master branch.
Working fine now.

Thanks

**Comment by R4scal** [comment]
Hi!

@ebrianne Can you release a new version with this feature?

**Comment by ebrianne** [comment]
> Hi!
> 
> @ebrianne Can you release a new version with this feature?

This is done. See new release v1.13
